### ISSUE TITLE
Hassio addon stops and has to be started manually 

### ISSUE THREAD

**Issue by h4nc** [ycardon/hassio-addons#1]
Looks like there is some issue with the add on.
Have it running since two days and it stopped two times. No idea what could cause this.
It works for around 12 hours and than stops.

**Comment by ycardon** [comment]
Ah yes, I remember you had the issue of gigaset-element-proxy crashing... I applied the same fix in the addon: restart whenever it crashes.

You can check the auto-update feature now :)

**Comment by h4nc** [comment]
Update not yet available. This probably takes some time?

**Comment by ycardon** [comment]
no it's immediate but you have to click the refresh button on the top right
of the HASSIO / ADD-ON STORE

**Comment by h4nc** [comment]
Thanks, already updated. It was there some hours ago, with our hitting refresh. Hopefully the issues is gone.
